// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mtsorella.Api.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mtsorella.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620131554_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mtsorella.Api.Domain.Achievements.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Medal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Announcements.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("PublishedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Badges.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Criteria")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Challenges.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CompletionPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Challenges.ChallengeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeadlineSnapshot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReviewedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "MemberId")
                        .IsUnique();

                    b.ToTable("ChallengeSubmissions");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Coaches.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("ShowOnWebsite")
                        .HasColumnType("boolean");

                    b.Property<int>("YearsInTeam")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Gallery.GalleryPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GalleryPhotos");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Highlights.MonthlyHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Month", "Mtsorella.Api.Domain.Highlights.MonthlyHighlight.Month#YearMonth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Month")
                                .HasColumnType("integer");

                            b1.Property<int>("Year")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MonthlyHighlights");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Inbox.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryOfInterest")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ChildDateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviousExperience")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Inbox.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Inbox.PartnershipInquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CooperationType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PartnershipInquiries");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("TeamRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("YearsInTeam")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Streak", "Mtsorella.Api.Domain.Members.Member.Streak#Streak", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Current")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("LastActiveOn")
                                .HasColumnType("date");

                            b1.Property<int>("Longest")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Performances.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Sponsors.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.TeamGoals.TeamGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CompletedOn")
                        .HasColumnType("date");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TeamGoals");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Trainings.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttendancePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatToBring")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Mtsorella.Api.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Achievements.Achievement", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.Placement", "Placement", b1 =>
                        {
                            b1.Property<Guid>("AchievementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int?>("Rank")
                                .HasColumnType("integer");

                            b1.HasKey("AchievementId");

                            b1.ToTable("Achievements");

                            b1.WithOwner()
                                .HasForeignKey("AchievementId");
                        });

                    b.Navigation("Placement")
                        .IsRequired();
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Announcements.Announcement", b =>
                {
                    b.OwnsMany("Mtsorella.Api.Domain.Announcements.AnnouncementReaction", "Reactions", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("On")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("AnnouncementId", "Id");

                            b1.ToTable("AnnouncementReaction");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId");
                        });

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Badges.Badge", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Icon", b1 =>
                        {
                            b1.Property<Guid>("BadgeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("BadgeId");

                            b1.ToTable("Badges");

                            b1.WithOwner()
                                .HasForeignKey("BadgeId");
                        });

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Challenges.Challenge", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "InstructionalVideo", b1 =>
                        {
                            b1.Property<Guid>("ChallengeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("Challenges");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.Navigation("InstructionalVideo")
                        .IsRequired();
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Challenges.ChallengeSubmission", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Video", b1 =>
                        {
                            b1.Property<Guid>("ChallengeSubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("ChallengeSubmissionId");

                            b1.ToTable("ChallengeSubmissions");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeSubmissionId");
                        });

                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.ChallengeScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("ChallengeSubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Completion")
                                .HasColumnType("integer");

                            b1.Property<int>("OnTimeBonus")
                                .HasColumnType("integer");

                            b1.Property<int>("Quality")
                                .HasColumnType("integer");

                            b1.HasKey("ChallengeSubmissionId");

                            b1.ToTable("ChallengeSubmissions");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeSubmissionId");
                        });

                    b.Navigation("Score");

                    b.Navigation("Video")
                        .IsRequired();
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Coaches.Coach", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Photo", b1 =>
                        {
                            b1.Property<Guid>("CoachId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("CoachId");

                            b1.ToTable("Coaches");

                            b1.WithOwner()
                                .HasForeignKey("CoachId");
                        });

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Gallery.GalleryPhoto", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Media", b1 =>
                        {
                            b1.Property<Guid>("GalleryPhotoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("GalleryPhotoId");

                            b1.ToTable("GalleryPhotos");

                            b1.WithOwner()
                                .HasForeignKey("GalleryPhotoId");
                        });

                    b.Navigation("Media")
                        .IsRequired();
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Highlights.MonthlyHighlight", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Photo", b1 =>
                        {
                            b1.Property<Guid>("MonthlyHighlightId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("MonthlyHighlightId");

                            b1.ToTable("MonthlyHighlights");

                            b1.WithOwner()
                                .HasForeignKey("MonthlyHighlightId");
                        });

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Members.Member", b =>
                {
                    b.OwnsMany("Mtsorella.Api.Domain.Members.EarnedBadge", "Badges", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("BadgeId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EarnedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MemberId", "Id");

                            b1.ToTable("EarnedBadge");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Photo", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsMany("Mtsorella.Api.Domain.Members.PointTransaction", "PointHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("OccurredOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Source")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("MemberId");

                            b1.ToTable("PointTransaction");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Badges");

                    b.Navigation("Photo");

                    b.Navigation("PointHistory");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Sponsors.Sponsor", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.MediaRef", "Logo", b1 =>
                        {
                            b1.Property<Guid>("SponsorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("SponsorId");

                            b1.ToTable("Sponsors");

                            b1.WithOwner()
                                .HasForeignKey("SponsorId");
                        });

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("Mtsorella.Api.Domain.Trainings.Training", b =>
                {
                    b.OwnsOne("Mtsorella.Api.Domain.Common.ValueObjects.Recurrence", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("TrainingId");

                            b1.PrimitiveCollection<string>("Days")
                                .IsRequired();

                            b1.Property<int>("Frequency");

                            b1.Property<DateOnly?>("Until");

                            b1.HasKey("TrainingId");

                            b1.ToTable("Trainings");

                            b1
                                .ToJson("Recurrence")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrainingId");
                        });

                    b.OwnsMany("Mtsorella.Api.Domain.Trainings.TrainingAttendance", "Attendances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ConfirmedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("HasEarnedPoints")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TrainingId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TrainingId");

                            b1.ToTable("TrainingAttendance");

                            b1.WithOwner()
                                .HasForeignKey("TrainingId");
                        });

                    b.Navigation("Attendances");

                    b.Navigation("Recurrence")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
